//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Karandash.Shared.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages_tr {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages_tr() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Karandash.Shared.Resources.Messages_tr", typeof(Messages_tr).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        internal static string GeneralMessageErrorOccured {
            get {
                return ResourceManager.GetString("GeneralMessageErrorOccured", resourceCulture);
            }
        }
        
        internal static string GreetingMessage {
            get {
                return ResourceManager.GetString("GreetingMessage", resourceCulture);
            }
        }
        
        internal static string AnUnhandledException {
            get {
                return ResourceManager.GetString("AnUnhandledException", resourceCulture);
            }
        }
        
        internal static string TermsAndPolicyNotAccepted {
            get {
                return ResourceManager.GetString("TermsAndPolicyNotAccepted", resourceCulture);
            }
        }
        
        internal static string EmailAlreadyExists {
            get {
                return ResourceManager.GetString("EmailAlreadyExists", resourceCulture);
            }
        }
        
        internal static string PasswordInvalid {
            get {
                return ResourceManager.GetString("PasswordInvalid", resourceCulture);
            }
        }
        
        internal static string UserRegistrationFailed {
            get {
                return ResourceManager.GetString("UserRegistrationFailed", resourceCulture);
            }
        }
        
        internal static string UserRegisteredSuccessfully {
            get {
                return ResourceManager.GetString("UserRegisteredSuccessfully", resourceCulture);
            }
        }
        
        internal static string InvalidUserRole {
            get {
                return ResourceManager.GetString("InvalidUserRole", resourceCulture);
            }
        }
        
        internal static string FieldRequired {
            get {
                return ResourceManager.GetString("FieldRequired", resourceCulture);
            }
        }
        
        internal static string PasswordsDoNotMatch {
            get {
                return ResourceManager.GetString("PasswordsDoNotMatch", resourceCulture);
            }
        }
        
        internal static string FieldMaxLength {
            get {
                return ResourceManager.GetString("FieldMaxLength", resourceCulture);
            }
        }
        
        internal static string FieldMinLength {
            get {
                return ResourceManager.GetString("FieldMinLength", resourceCulture);
            }
        }
        
        internal static string InvalidEmailFormat {
            get {
                return ResourceManager.GetString("InvalidEmailFormat", resourceCulture);
            }
        }
        
        internal static string FieldName_Surname {
            get {
                return ResourceManager.GetString("FieldName-Surname", resourceCulture);
            }
        }
        
        internal static string FieldName_Name {
            get {
                return ResourceManager.GetString("FieldName-Name", resourceCulture);
            }
        }
        
        internal static string FieldName_Password {
            get {
                return ResourceManager.GetString("FieldName-Password", resourceCulture);
            }
        }
        
        internal static string FieldName_ConfirmPassword {
            get {
                return ResourceManager.GetString("FieldName-ConfirmPassword", resourceCulture);
            }
        }
        
        internal static string FieldName_Email {
            get {
                return ResourceManager.GetString("FieldName-Email", resourceCulture);
            }
        }
        
        internal static string EmailBelongsToDeletedUser {
            get {
                return ResourceManager.GetString("EmailBelongsToDeletedUser", resourceCulture);
            }
        }
        
        internal static string InvalidEmailOrPassword {
            get {
                return ResourceManager.GetString("InvalidEmailOrPassword", resourceCulture);
            }
        }
        
        internal static string AccountDeleted {
            get {
                return ResourceManager.GetString("AccountDeleted", resourceCulture);
            }
        }
        
        internal static string InvalidRefreshToken {
            get {
                return ResourceManager.GetString("InvalidRefreshToken", resourceCulture);
            }
        }
        
        internal static string RefreshTokenExpired {
            get {
                return ResourceManager.GetString("RefreshTokenExpired", resourceCulture);
            }
        }
        
        internal static string UserNotFoundForPasswordReset {
            get {
                return ResourceManager.GetString("UserNotFoundForPasswordReset", resourceCulture);
            }
        }
        
        internal static string PasswordReset_EmailMessage {
            get {
                return ResourceManager.GetString("PasswordReset-EmailMessage", resourceCulture);
            }
        }
        
        internal static string FieldName_NewPassword {
            get {
                return ResourceManager.GetString("FieldName-NewPassword", resourceCulture);
            }
        }
        
        internal static string FieldName_Token {
            get {
                return ResourceManager.GetString("FieldName-Token", resourceCulture);
            }
        }
        
        internal static string InvalidPasswordToken {
            get {
                return ResourceManager.GetString("InvalidPasswordToken", resourceCulture);
            }
        }
        
        internal static string PasswordReset_Success {
            get {
                return ResourceManager.GetString("PasswordReset-Success", resourceCulture);
            }
        }
        
        internal static string UserRoleAreNotAllowed {
            get {
                return ResourceManager.GetString("UserRoleAreNotAllowed", resourceCulture);
            }
        }
        
        internal static string InvalidPageSize {
            get {
                return ResourceManager.GetString("InvalidPageSize", resourceCulture);
            }
        }
        
        internal static string InvalidPageNumber {
            get {
                return ResourceManager.GetString("InvalidPageNumber", resourceCulture);
            }
        }
        
        internal static string OldPasswordIncorrect {
            get {
                return ResourceManager.GetString("OldPasswordIncorrect", resourceCulture);
            }
        }
        
        internal static string NewPasswordCannotBeSameAsOld {
            get {
                return ResourceManager.GetString("NewPasswordCannotBeSameAsOld", resourceCulture);
            }
        }
        
        internal static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
        
        internal static string AccountDeactivatedSuccessfully {
            get {
                return ResourceManager.GetString("AccountDeactivatedSuccessfully", resourceCulture);
            }
        }
        
        internal static string AccountDeactivationFailed {
            get {
                return ResourceManager.GetString("AccountDeactivationFailed", resourceCulture);
            }
        }
        
        internal static string SystemRoleDeactivationNotAllowed {
            get {
                return ResourceManager.GetString("SystemRoleDeactivationNotAllowed", resourceCulture);
            }
        }
    }
}
